/* ============================================================
   CKfablab 專案資料
   新增專案：複製一個物件、填入內容即可，網站自動渲染。
   category: ai | interact | fab | edu | arch
   image:    'assets/projects/xxx.jpg'（未填則顯示幾何 placeholder）
   featured: true 會出現在首頁精選（最多 4 個）
   — 詳情頁欄位（有 slug 者卡片會連到 project.html?id=slug）—
   slug:      網址代號
   gallery:   ['assets/projects/gallery/xxx.jpg', ...]
   detail_zh: ['段落一', '段落二', ...]
   detail_en: ['paragraph 1', ...]
   facts:     [['年份','事實（展覽／得獎）'], ...]
   ============================================================ */

const PROJECTS = [
  // ---------- 2026 近期活動 ----------
  {
    title_en: 'Intergenerational Play Hackathon',
    title_zh: '跨代童玩 Hackathon',
    year: '2026.07',
    category: 'interact',
    featured: true,
    image: 'assets/projects/hackathon.jpg',
    desc_en: 'Grandparent-grandchild play × AI × web games × physical sensing — planned and led under the MOE 4th-phase USR seed project “Intergenerational Smart Co-Creation” (PI). 12 families, five awards, 13 playful works linking physical and digital: AI-designed games, six kinds of sensors, AI-generated 3D-printed characters. Outcomes to be exhibited at the YZU Art Center. Click to watch the video.',
    desc_zh: '祖孫共玩 × AI × 網頁遊戲 × 實體感測—教育部第四期 USR 萌芽計畫「跨代智慧共創」（主持人）規劃執行。12 個家庭 PK 五大獎項，完成 13 種實虛連結的創意童玩：AI 設計遊戲、6 種感測器、AI 生成＋3D 列印角色。成果將於藝術中心展出。點擊觀看活動影片。',
    link: 'assets/media/hackathon-2026.mp4'
  },
  {
    title_en: 'AI × Design Practitioner Industry Workshop',
    title_zh: 'AI × 設計職人產業實戰工作坊',
    year: '2026',
    category: 'ai',
    featured: true,
    image: 'assets/projects/aia-workshop.jpg',
    desc_en: 'Workshop series planned and executed by CK with Taiwan AI Academy (AIA) — two sessions: “Design Method: AI Design Work System” by invited mentor Shao Wei-Yen of CHU-studio (5/09, NTUST), and CK’s “Product Space: Rhino × AI Rendering Workflow” (6/13, YZU).',
    desc_zh: 'CK 與台灣人工智慧學校（AIA）策劃執行的系列工作坊—兩場次：邀請竹工凡木邵唯晏主講「設計方法：AI 設計工作系統」（5/09，台科大）；CK 主講「產品空間：Rhino × AI 渲染工作流」（6/13，元智）。',
    link: '#'
  },

  // ---------- 2020s：AI 與生成設計 ----------
  {
    title_en: 'AI Creative Design Thinking',
    title_zh: 'AI 創意設計思考',
    year: '2024–',
    category: 'ai',
    featured: true,
    image: 'assets/projects/ai-creative-design-thinking.jpg',
    desc_en: 'A pedagogical framework and studio course exploring how designers co-create with generative AI — from prompt-based ideation to vibe coding functional prototypes.',
    desc_zh: '探索設計師如何與生成式 AI 共創的教學框架與課程：從提示式發想到以 vibe coding 完成可運作原型。',
    link: '#'
  },
  {
    title_en: 'Vibe Coding in Design Education',
    title_zh: 'Vibe Coding 設計教育研究',
    year: '2025–',
    category: 'ai',
    image: 'assets/projects/gallery/xArch_2026_CK_01.jpg',
    desc_en: 'Research on conversational AI programming as a design medium — published as “Vibe Coding with GPT: A Human–AI Collaborative Framework for Creativity and Learning in Design Education” (xArch 2026, Springer).',
    desc_zh: '以對話式 AI 程式作為設計媒材的研究—成果〈Vibe Coding with GPT: A Human–AI Collaborative Framework for Creativity and Learning in Design Education〉發表於 xArch 2026（Springer）。',
    link: '#'
  },
  {
    title_en: 'Cognitive Studies of Human-AI Design',
    title_zh: 'GenAI 設計認知研究（眼動實驗）',
    year: '2025–',
    category: 'ai',
    image: 'assets/projects/genai-eyetracking.jpg',
    desc_en: 'Eye-tracking and think-aloud studies of how designers’ cognition shifts when co-creating with GenAI — Best Presentation Award at AIVR 2025 (Osaka); extended study submitted to CAAD Futures.',
    desc_zh: '以眼動儀與放聲思考探討設計師與 GenAI 共創時的認知轉變—獲 AIVR 2025（大阪）最佳發表獎，延伸研究投稿 CAAD Futures。',
    award: 'AIVR 2025 最佳發表獎',
    award_en: 'Best Presentation Award — AIVR 2025, Osaka',
    link: '#'
  },
  {
    title_en: 'Immersive Intelligence (AI-VR)',
    title_zh: '臨場智匯（AI-VR）',
    year: '2025–26',
    category: 'ai',
    image: 'assets/projects/aivr.jpg',
    desc_en: 'AI-VR integrated innovation for clinical skills and communication training — NSTC practical research project (PI), with VR standard-patient scenarios driven by conversational AI.',
    desc_zh: '「臨場智匯：AI-VR 融合之臨床技能與溝通教學革新方案」—國科會實務型研究專案（主持人），以對話式 AI 驅動 VR 標準病人情境。',
    link: '#'
  },
  {
    title_en: 'Generative Art Series',
    title_zh: '生成藝術系列',
    year: '2023–',
    category: 'ai',
    image: 'assets/projects/generative-art.jpg',
    desc_en: 'Algorithmic works in p5.js — flow fields, particle systems and emergent pattern studies. The hero animation on this site is one of them.',
    desc_zh: 'p5.js 演算法創作系列—流場、粒子系統與湧現圖紋研究。本站首頁的動態視覺即為其中之一。',
    link: '#'
  },

  // ---------- 互動與高齡科技（含 MOST 計畫作品）----------
  {
    title_en: 'Companionship, Auto-Generating (Exhibition)',
    title_zh: '陪伴，自動生成中（展覽）',
    year: '2025',
    category: 'interact',
    featured: true,
    image: 'assets/projects/companionship-exhibition.jpg',
    desc_en: 'Exhibition of AI companion works co-created for elder care — You Should Know Your Meds, Walking Down Memory Lane, Singing Star, Piggy Bank Planner, Follow Me — opened June 2025.',
    desc_zh: 'AI 陪伴互動作品展：你藥知道、憶起散步、我是歌王歌后、理財豬公、請你跟我這樣做—2025 年 6 月開展。',
    link: '#'
  },
  {
    title_en: 'Dementia Care Companion (LINE Bot)',
    title_zh: '失智小幫手',
    year: '2025–',
    category: 'interact',
    desc_en: 'An AI conversational companion on LINE supporting dementia caregivers and community care sites, developed with local partners in Zhongli.',
    desc_zh: '以 LINE 為載體的 AI 對話夥伴，支援失智照顧者與社區關懷據點，與中壢在地夥伴共同發展。',
    link: '#'
  },
  {
    title_en: 'Intergenerational Smart Co-Creation (USR)',
    title_zh: '跨代智慧共創（USR）',
    year: '2025–27',
    category: 'interact',
    image: 'assets/projects/usr-cocreation.jpg',
    desc_en: '“Intergenerational Smart Co-Creation: Design Thinking Leading Technology and Well-Being” — MOE 4th-phase USR seed project (PI), connecting design students with elder communities through co-design and creative technology.',
    desc_zh: '教育部第四期 USR 萌芽計畫「跨代智慧共創：設計思考引領科技與幸福」（主持人）—透過共創工作坊與創意科技，連結設計學生與高齡社區。',
    link: '#'
  },
  {
    title_en: 'Presence Stickers',
    title_zh: '存在貼片',
    year: '2022–23',
    category: 'interact',
    desc_en: 'IoT sensing system perceiving indoor spatial behaviour for elders’ smart living at home (NSTC project, PI).',
    desc_zh: '應用於高齡者居家智慧生活之室內空間行為感知 IoT 智慧系統（國科會計畫，主持人）。',
    link: '#'
  },
  {
    title_en: 'EMO Pillow',
    title_zh: 'EMO Pillow 情緒感知枕',
    year: '2020–22',
    category: 'interact',
    desc_en: 'Emotion-aware intergenerational care product research — two-year NSTC project (PI) extending the Pillow Fight lineage with affective sensing.',
    desc_zh: '具情緒感知之代間關懷科技產品研究—兩年期國科會計畫（主持人），以情緒感測延伸枕頭戰系列。',
    link: '#'
  },
  {
    title_en: 'Pillow Fight',
    title_zh: '枕頭戰：我要我們憶起玩',
    year: '2019',
    category: 'interact',
    image: 'assets/projects/pillow-fight.jpg',
    desc_en: 'An intergenerational interactive game device for day-care centers, commercialized in 2019 and adopted across Taiwan.',
    desc_zh: '代間互動遊戲裝置，2019 年商品化，銷售至台灣各地日照中心與關懷據點。',
    award: '史丹佛銀髮設計競賽 全球第三名',
    award_en: 'Stanford Design Challenge — Global 3rd Place',
    link: 'pillow-fight-2019.html',
    spec_page: 'pillow-fight-2019.html',
    slug: 'pillow-fight',
    detail_en: ['Pillow Fight is a lively, easy-to-play video game designed for grandparents and grandchildren to play together. Built on the principle of behavioural adaptivity, the technology hides inside familiar living objects — soft pillows become game controllers — so that players of any age can join without fear of technology.','Real users — elders and children — participated throughout the design process. Their feedback shaped gentle, effortless controls for elders and playful, competitive pacing for children. Teams can play side by side in the same room or connect remotely, pairing the dedicated pillows with a tablet app to bring family members together.','Behind the product is a story dedicated to a mother. In late 2016, while her mother was in the final stage of cancer, Chor-Kheng Lim travelled repeatedly between Taiwan and Malaysia — a two-month-old daughter and a four-year-old son in tow — to be by her side. She noticed that, apart from the caregiver, what stayed closest to her mother was a pillow she rarely let go of: not merely company, but a source of comfort and safety.','After her mother passed in 2017, she ran nearly thirty intergenerational-care workshops within a year. A participant’s remark reminded her of a wish she had once made to her mother, and she threw herself into an entirely unfamiliar field — sensors, a game app, pillow hardware, sewing, user testing — doing every step herself to bring Pillow Fight to life in a single year. In 2019 it won 3rd place worldwide at the Stanford Center on Longevity Design Challenge, an honour she dedicated to the mother she misses most. More than a thousand elders have now played with it. (In Malaysia, when a baby is born, mothers and grandmothers often hand-sew small pillows for the child; Lim’s own mother sewed many such pillows, full of love, for her grandchildren.)'],
    detail_zh: ['一同體驗、憶起歡樂—用抱枕帶來的安全感傳遞溫暖，用遊戲中的歡笑聲乘載共同的美好回憶。本設計以祖孫共玩為目標，發展一套孩童及長輩都容易操作的生動有趣電玩遊戲。設計基於行為「適應性」為主軸，將科技隱藏於生活物件中，著重於不分年紀都能適應的遊戲操作行為。','設計過程加入了真實使用者（長者與孩童）的參與：考量年長者動作不宜過大、對科技產品有所畏懼，操作簡單不繁瑣、動作輕柔不費勁；同時參酌孩童對遊戲的想像，角色活潑、加上時間限制增添競爭與刺激。遊戲可在同一空間共玩，也可透過專屬抱枕與平板 APP 遠距連線，讓彼此的關係更加緊密。','在產品的背後，是一段獻給母親的故事。2016 年底母親癌末期間，林楚卿帶著剛出生兩個月的女兒與四歲的兒子往返台灣與馬來西亞陪伴她；她發現最常伴著母親的，除了看護，就是那顆幾乎不離身的抱枕—抱枕不只是陪伴，更是安全感的來源。','2017 年母親離世後，她在一年間辦理了近 30 場代間關懷工作坊；一次學員的回饋讓她想起心中對母親許下的心願，於是投入這個全然陌生的領域—從感測器、App 遊戲、抱枕硬體到縫製與使用者測試全程親力親為，以一年時間完成【枕頭戰】。2019 年獲國際史丹佛銀髮設計競賽全球第三名，她將這份殊榮獻給最想念的母親；目前已有逾千位長者透過枕頭戰同樂。（在馬來西亞，家中有新生兒時，母親或祖母會親手縫製小抱枕；林楚卿的母親也曾為孫子縫下許多充滿愛的抱枕。）'],
    facts: [['2019','桃園科技藝術節（桃園市政府文化局主辦，桃園展演中心，10.15–11.3）'],['2019','全齡快樂進行市（衛生福利部主辦，松山文創園區一號倉庫，11.15–11.19）'],['2019','國際史丹佛銀髮設計競賽 全球大賽第三名（僅次於史丹佛及柏克萊大學）'],['2020','科技部創新創業激勵競賽（FITI）創業潛力獎'],['2018','史丹佛銀髮設計競賽 亞洲優選・教育部智慧生活三創競賽 優勝獎・社會創新 創新構想獎']],
    venues_page: 'pillow-fight-venues.html',
    press_pdf: 'assets/projects/gallery/枕頭戰_新聞合併檔.pdf',
    video_mp4: 'assets/projects/gallery/pf-gameplay.mp4',
    venues_note_en: 'Pillow Fight travelled to elder day-care centres, dementia-care units, kindergartens and community associations across Taiwan — a record of the sites where elders and children played together.',
    venues_note_zh: '枕頭戰巡迴台灣各地日照中心、失智照護據點、幼兒園與社區發展協會，實地陪伴長者與孩童同樂—以下是各場域應用的紀錄。',
    venues: [
      { img: 'assets/projects/gallery/pillow-fight-5.jpg',  name: '台中西屯福氣長青快樂學堂', org: '弘道老人福利基金會', date: '2020.09.11' },
      { img: 'assets/projects/gallery/pillow-fight-6.jpg',  name: '桃園地球村代間藝術教育', date: '2020.08.18' },
      { img: 'assets/projects/gallery/pillow-fight-7.jpg',  name: '新竹婕之寶幼兒園', date: '2020.08.17' },
      { img: 'assets/projects/gallery/pillow-fight-8.jpg',  name: '桃園平鎮區公所', date: '2020.07.09' },
      { img: 'assets/projects/gallery/pillow-fight-9.jpg',  name: '石碇楓子林公共托老中心', org: '財團法人老五老基金會', date: '2019.11.28' },
      { img: 'assets/projects/gallery/pillow-fight-10.jpg', name: '彰化憶智樂活之家', org: '弘道老人福利基金會', date: '2020.09.09' },
      { img: 'assets/projects/gallery/pillow-fight-11.jpg', name: '新北三峽台北榮家（失智照護區）', date: '2020.08.12' },
      { img: 'assets/projects/gallery/pillow-fight-12.jpg', name: '新北三峽台北榮家', date: '2020.05.29' },
      { img: 'assets/projects/gallery/pillow-fight-13.jpg', name: '桃園八德廣興社區發展協會', date: '2020.07.06' },
      { img: 'assets/projects/gallery/pillow-fight-14.jpg', name: '桃園地球村代間藝術教育', org: '設計原型使用者測試', date: '2019.06.11' },
      { img: 'assets/projects/gallery/pillow-fight-15.jpg', name: '中壢新明社區長照機構', date: '2020.08.11' },
      { img: 'assets/projects/gallery/pillow-fight-16.jpg', name: '桃園龍岡社區發展協會', date: '2020.08.18' },
      { img: 'assets/projects/gallery/pillow-fight-17.jpg', name: '桃園平鎮 C 型巷弄長照站', date: '2020.07.27' },
      { img: 'assets/projects/gallery/pillow-fight-18.jpg', name: '新竹喬曼嘉幼兒園', date: '2020.07.02' }
    ],
    brand: [
      { t:'p', zh:'關於【枕頭戰】的產生，其實背後有洋蔥—這是 CK（團隊總監林楚卿）要獻給媽媽的作品。', en:'The making of Pillow Fight has a tender backstory — it is a work Chor-Kheng Lim (CK), the team’s director, created for her mother.' },
      { t:'p', zh:'2016 年底，CK 在媽媽癌末生病期間，總是帶著剛出生兩個月的女兒與四歲的兒子，奔波台灣、馬來西亞兩地，只為讓自己與孩子能有更多時間陪伴母親／外婆。但媽媽的身體狀況，已再也無法像從前那樣陪孫子們玩樂。', en:'In late 2016, while her mother was in the final stage of cancer, CK travelled constantly between Taiwan and Malaysia — a two-month-old daughter and a four-year-old son in tow — so that she and her children could spend more time with her mother. Yet her mother could no longer play with the grandchildren as she once had.' },
      { t:'p', zh:'陪伴母親的最後時光，CK 發現最常伴在她身邊的，除了看護，就是那顆幾乎不離身的抱枕—抱枕對母親而言不只是陪伴，更是安全感的來源。於是 CK 思索著能為她做些什麼，但因諸多壓力在身，這個想法只能先暫放心中。', en:'In those last days, CK noticed that, apart from the caregiver, what stayed closest to her mother was a pillow she rarely let go of — not merely company, but a source of comfort and safety. CK began to wonder what she could make, but under the weight of everything, the idea had to wait.' },
      { t:'p', zh:'2017 年 2 月母親離開後，CK 以更忙碌的工作忘卻悲痛；失去母親的一年間，她辦了近 30 場代間關懷工作坊。某次工作坊中，一句學員的回饋讓她想起曾對母親許下的心願，於是她投入這個全然陌生的領域—從感測器研究製作、App 遊戲設計開發、抱枕硬體、材料採買到縫製與使用者測試，每個環節都親力親為，花一年時間讓【枕頭戰】誕生。', en:'After her mother passed in February 2017, CK buried her grief in work, running nearly thirty intergenerational-care workshops within the year. At one, a participant’s remark reminded her of the wish she had made to her mother, and she threw herself into an entirely unfamiliar field — sensor research, game-app design, pillow hardware, materials, sewing and user testing — doing every step herself to bring Pillow Fight to life in a single year.' },
      { t:'p', zh:'從 2018 年起帶著它南征北討，最終獲得 2019 年國際史丹佛銀髮設計競賽全球大賽第三名。這份殊榮，CK 想與最親愛、最想念的媽媽分享。', en:'From 2018 she took it across Taiwan and beyond, and in 2019 it won 3rd place worldwide at the Stanford Center on Longevity Design Challenge — an honour she wished to share with the mother she misses most.' },
      { t:'img', src:'assets/projects/gallery/pf-brand-1.jpg' },
      { t:'p', zh:'這張 CK 當時很不忍拍下的畫面，成了驅使【枕頭戰】誕生最大的動力，讓它在短短一年成為商品，隔年進化到功能更完善的第二代，並預計於 2021 年推出結合 IoT 與雲端檢測的第三代。雖然 CK 已無法再讓媽媽與孫子們共享抱枕的天倫之樂，但她想把「美好的親子關係」傳遞給更多人。目前已有逾千位長者透過枕頭戰同樂—看見每一位長輩的笑容，再苦再累 CK 都願意。', en:'This image, which CK could barely bring herself to take, became the greatest force behind Pillow Fight — turning it into a product within a year, a more refined second generation the next, with a third generation combining IoT and cloud monitoring planned for 2021. Though she can no longer share the joy of the pillow between her mother and her children, CK wants to pass that “beautiful family bond” on to others. More than a thousand elders have now played with it — and for every smile, she says, no effort is too much.' },
      { t:'img', src:'assets/projects/gallery/pf-brand-2.jpg' },
      { t:'img', src:'assets/projects/gallery/pf-brand-3.jpg' },
      { t:'h', zh:'習俗小故事', en:'A small custom' },
      { t:'p', zh:'CK 是馬來西亞籍，抱枕對她有很特殊的情感連結與意義。在馬來西亞，有些家庭在小 baby 出生時，會由會裁縫的媽媽或外婆、祖母親手縫製小抱枕給孩子；CK 的媽媽就親手縫了許多小抱枕給孫子，還會隨寶寶長大縫製合適的大小—那是充滿滿滿愛的抱枕。', en:'CK is Malaysian, and the pillow holds a special meaning for her. In Malaysia, when a baby is born, a mother or grandmother who can sew will often hand-make small pillows for the child; CK’s own mother sewed many for her grandchildren, resizing them as the babies grew — pillows filled with love.' }
    ],
    story: [
      { t:'h',   zh:'抱枕 ＋ 電玩 ＋ 祖孫 ＝ ？', en:'Pillows + video games + generations = ?' },
      { t:'p',   zh:'CKfablab 團隊結合此三項元素，並與真實使用者（長者與孩童）共同研發，利用自小即給我們安全感的「抱枕」，藉由最直覺自然的方式將科技隱藏於生活中，開發出適合跨代共玩的遊戲產品。', en:'The CKfablab team combined these three elements and co-developed the product with real users — elders and children — hiding technology inside the pillow that has given us a sense of security since childhood, in the most intuitive, natural way, to create a game the generations can play together.' },
      { t:'sub', zh:'「枕頭戰！ 我要我們憶起玩」', en:'“Pillow Fight! Let’s remember to play together”' },
      { t:'img', src:'assets/projects/gallery/pf-demo-1.png' },
      { t:'p',   zh:'團隊希望藉此拉近祖孫距離，共創更多美好回憶—抱枕＋電玩＋祖孫的總和，是帶來更多笑容、留住最美的記憶。', en:'The team hopes to bring grandparents and grandchildren closer and create happy memories together — the sum of pillow, game and family is more smiles and moments worth keeping.' },
      { t:'link', zh:'進入了解〈品牌故事〉', en:'Read the story behind →', href:'pillow-fight-brand.html' },
      { t:'img', src:'assets/projects/gallery/pf-demo-2.png' },
      { t:'img', src:'assets/projects/gallery/pf-demo-3.jpg' },
      { t:'p',   zh:'研發過程中，我們得到許多長者、孩童與機構的協助與回饋；帶著抱枕四處奔波的日子雖然辛苦，但看見這些笑顏，足以驅動我們不停測試、修改、突破。', en:'Throughout development we received help and feedback from many elders, children and institutions. The days of carrying pillows from place to place were tiring, but those smiles kept us testing, refining and pushing forward.' },
      { t:'link', zh:'進入了解〈場域應用〉', en:'See where it has travelled ↓', to:'venues' },
      { t:'img', src:'assets/projects/gallery/pf-demo-4.mp4' },
      { t:'h',   zh:'產品介紹', en:'The Product' },
      { t:'p',   zh:'考量年長者動作不宜過大、對科技操作有所畏懼，設計操作簡單不繁瑣、動作輕柔不費勁；結合互動科技的枕頭在拆除控制盒後仍可清洗。', en:'Mindful that elders may find large movements hard and technology daunting, the controls are simple and gentle; with the control box removed, the interactive pillow can still be washed.' },
      { t:'img', src:'assets/projects/gallery/pf-demo-5.png', label:true },
      { t:'p',   zh:'只需打開控制盒開關，即可藍芽連線 App 開始遊戲。', en:'Just switch on the control box and connect the app over Bluetooth to start playing.' },
      { t:'img', src:'assets/projects/gallery/pf-demo-6.mp4' },
      { t:'img', src:'assets/projects/gallery/pf-demo-7.mp4' },
      { t:'img', src:'assets/projects/gallery/pf-demo-8.png', label:true },
      { t:'p',   zh:'拍打抱枕就能玩遊戲，不需學習如何操控複雜的遙控器。', en:'Pat the pillow to play — no complicated remote to learn.' },
      { t:'img', src:'assets/projects/gallery/pf-demo-9.png' },
      { t:'img', src:'assets/projects/gallery/pf-demo-10.mp4' },
      { t:'img', src:'assets/projects/gallery/pf-demo-11.png', label:true },
      { t:'p',   zh:'多款遊戲類型：競爭型（種菜、狗吃骨頭、恐龍搶肉、開禮物）、協同型（旋律、抓魚、煙火、節奏等聽覺遊戲）、復健型（打地鼠、射氣球，搭配多顆抱枕）。', en:'Many game types: competitive (planting vegetables, a dog fetching bones, dinosaurs grabbing meat, opening gifts), cooperative audio games (melody, catching fish, fireworks, rhythm) and rehabilitative games (whack-a-mole, balloon-popping with several pillows).' },
      { t:'img', src:'assets/projects/gallery/pf-demo-12.mp4' },
      { t:'img', src:'assets/projects/gallery/pf-demo-13.png', label:true },
      { t:'p',   zh:'多種模式，單挑或合作任君挑選—單人、雙人、多人皆可。', en:'Several modes to choose from — solo, duel or cooperative, for one, two or many players.' },
      { t:'img', src:'assets/projects/gallery/pf-demo-14.mp4' },
      { t:'img', src:'assets/projects/gallery/pf-demo-15.png', label:true },
      { t:'p',   zh:'遊戲於居家、公園、車內、輪椅……想玩就玩！', en:'Play at home, in a park, in the car or in a wheelchair — whenever the mood strikes.' },
      { t:'img', src:'assets/projects/gallery/pf-demo-16.mp4' },
      { t:'img', src:'assets/projects/gallery/pf-demo-17.png', label:true },
      { t:'p',   zh:'發揮你的想像力—手、腳、身體任何部位碰觸抱枕都能玩。', en:'Use your imagination — touch the pillow with a hand, a foot or any part of the body.' },
      { t:'img', src:'assets/projects/gallery/pf-demo-18.mp4' }
    ],
  },
  {
    title_en: 'Wonder Corner 2×2',
    title_zh: '奇觀角落 2×2',
    year: '2019',
    category: 'interact',
    image: 'assets/projects/wonder-corner.jpg',
    desc_en: 'A 2×2 m interactive IoT space installation — everyday objects awaken to touch.',
    desc_zh: '2×2 米互動空間裝置—以觸摸喚醒日常物件的 IoT 奇觀。',
    link: 'project.html?id=wonder-corner',
    slug: 'wonder-corner',
    gallery: ['assets/projects/gallery/wonder-corner-1.jpg','assets/projects/gallery/wonder-corner-2.jpg','assets/projects/gallery/wonder-corner-3.jpg','assets/projects/gallery/wonder-corner-4.jpg'],
    detail_en: ['“Touch” is the most intuitive behaviour in our daily lives. Wonder Corner uses touch between people and objects as its trigger, building IoT communication channels among living objects and furniture so each becomes an intelligent, adaptive character.','Within a 2×2 m interactive installation, familiar objects — floor, sofa, television, pendant lamp, pillows — are connected through IoT. As visitors enter the space and interact naturally, a chain of surprising sensory experiences begins.'],
    detail_zh: ['「觸摸」這樣最為直覺的行為，一直存在我們的日常生活中。作品藉由「人」與「物」之間的觸碰行為作為觸發條件，結合物聯網（IoT）技術，在生活物件或家具之間建立溝通渠道，以直覺的互動讓每個生活物件都成為智能適應角色。','此作品為 2×2 米的互動空間裝置，透過一般生活熟悉物件—地板、沙發、電視、吊燈、抱枕—連結 IoT 智慧互動。參觀者進入空間與物件自然互動，觸發物聯網連結後，驚奇的感官體驗即將開始。'],
    facts: [['2019','桃園科技藝術節（桃園市政府文化局主辦，桃園展演中心，10.15–11.3）']]
  },
  {
    title_en: 'Memory of Things (MoT)',
    title_zh: '物.憶.網 MoT',
    year: '2015–16',
    category: 'interact',
    desc_en: 'Interactive memory product design for elders’ reminiscence activities.',
    desc_zh: '高齡者懷舊互動產品設計，連結舊物與記憶。',
    award: '2nd Int’l Conf. on Digital Fabrication 最佳 Demo 獎（東京）',
    award_en: 'Best Demo Award — 2nd Int’l Conference on Digital Fabrication, Tokyo',
    link: '#'
  },
  {
    title_en: 'Steps & Flowers',
    title_zh: 'Steps & Flowers',
    year: '2013–15',
    category: 'interact',
    desc_en: 'Multi-modal interactive platform for elders in home environments — NSTC project (PI) developed toward commercialization; includes the interactive 3D-printed customized planter.',
    desc_zh: '居家環境下銀髮族多元互動平台之開發與商品化應用（國科會計畫，主持人），含互動式 3D 列印客製化花器。',
    link: '#'
  },
  {
    title_en: 'Inch Grass Sound',
    title_zh: '吋草音',
    year: '2012–2015',
    category: 'interact',
    image: 'assets/projects/inch-grass.jpg',
    desc_en: 'Intergenerational interactive planter design series — sound, sensing and companionship.',
    desc_zh: '世代互動花器設計系列—聲音、感測與陪伴。',
    link: 'project.html?id=inch-grass',
    slug: 'inch-grass',
    gallery: ['assets/projects/gallery/inch-grass-1.jpg','assets/projects/gallery/inch-grass-2.jpg','assets/projects/gallery/inch-grass-3.jpg'],
    detail_en: ['A long-term series of intergenerational interactive planters (2012–2015), weaving sound, sensing and daily plant care into gentle companionship between generations.'],
    detail_zh: ['「吋草音」為世代互動花器設計系列（2012–2015），將聲音、感測與日常植栽照護編織進世代之間的溫柔陪伴。']
  },
  {
    title_en: 'Spring Breeze',
    title_zh: '望春風',
    year: '2010',
    category: 'interact',
    image: 'assets/projects/spring-breeze.jpg',
    desc_en: 'NSC forward-looking concept design: creative products and reminiscence spaces for elders with dementia.',
    desc_zh: '國科會前瞻概念設計計畫：失智老人創意應用產品及情境回憶空間概念設計。',
    link: 'project.html?id=spring-breeze',
    slug: 'spring-breeze',
    gallery: ['assets/projects/gallery/spring-breeze-1.jpg'],
    detail_en: ['“Spring Breeze” — an NSC forward-looking concept design project on creative products and situated reminiscence spaces for elders with dementia (2010). The related interactive shoe cabinet “Welcoming Spring” won Best Design of the Year in the NSC Forward-Looking Design program.'],
    detail_zh: ['「望春風」為國科會前瞻設計計畫（2010）：失智老人創意應用產品及情境回憶空間概念設計。同期作品「迎春」互動鞋櫃獲科技部前瞻設計年度最佳設計作品獎。']
  },

  // ---------- 數位製造 ----------
  {
    title_en: 'WAX — Sustainable Wax Morphogenesis',
    title_zh: 'WAX 永續蠟材形態製造',
    year: '2024–',
    category: 'fab',
    image: 'assets/projects/wax.jpg',
    desc_en: 'Wax form-finding through an AI-assisted robotic arm for sustainable design and manufacturing — NSTC grant “Human-AI Collaborative Morphogenesis” (2026); presented at GCSM 2025 and as an invited lecture at the University of Bologna; journal article in submission to Electronics.',
    desc_zh: 'AI 輔助機器手臂之蠟材找形研究，面向永續設計與製造—國科會 115 年度計畫「人機協作形態創生：整合生成式 AI 與手勢控制的蠟材設計系統」；於 GCSM 2025 發表並受邀於波隆那大學演講，期刊論文投稿 Electronics 中。',
    link: '#'
  },
  {
    title_en: 'MU — Nurturing Wonderland',
    title_zh: 'MU 孕育的秘境',
    year: '2017',
    category: 'fab',
    image: 'assets/projects/mu.jpg',
    desc_en: 'Outdoor installation for the Taoyuan Land Art Festival — a milk-can castle built for the artist’s son.',
    desc_zh: '桃園地景藝術節戶外裝置—送給兒子的「奶罐城堡」。',
    link: 'project.html?id=mu',
    slug: 'mu',
    gallery: ['assets/projects/gallery/mu-1.jpg'],
    detail_en: ['An outdoor installation on the grassland beside a dairy farm, MU begins from “the land nurturing life”: grass feeds the cattle, cattle give milk, and milk nurtures new life. Land, cattle and babies exist in a circle of mutual nurturing.','The recycled milk-powder cans are those collected since the designer’s own son was born. Rolled up like grass rising from the land, the spiral structure (120×50×150 cm) combines a metal frame, 3D-printed fixings, laser-cut growth silhouettes and cowbells.','Visitors can crawl inside — like childhood memories of hiding in park pipes — to experience sunlight filtering through the cut silhouettes, casting the story of a growing life. After the exhibition, the installation was given to the son as his “milk-can castle”.'],
    detail_zh: ['作品為戶外裝置，放置於牛場旁的草地上，以「大地孕育生命」作為創作發想：牧草餵養牛群，牛奶哺育新生命—大地、牛群、寶寶之間存在著相互「孕育」的循環關係。','裝置所使用的回收奶粉罐，是設計者四歲兒子從出生至今收集而來。整體造型為牧草從大地捲起之意象與奶粉罐筒狀的結合（120×50×150 cm）：金屬主結構、3D 列印次結構固定奶粉罐、雷射切割成長輪廓，並掛上牛鈴鐺。','民眾可鑽進裝置內部，猶如小時候窩在公園水泥柱中的經驗，感受陽光穿過切割輪廓投下的成長光影；清風吹過，奶粉罐與牛鈴輕碰作響。展覽結束後，這座裝置送給了兒子，成為他的「奶罐城堡」。'],
    facts: [['2017','桃園地景藝術節（桃園市政府文化局委託設置）']]
  },
  {
    title_en: 'Setiakon Freeform Lobby',
    title_zh: 'Setiakon 自由形體大廳設計',
    year: '2017',
    category: 'fab',
    image: 'assets/projects/setiakon.jpg',
    desc_en: 'Parametric freeform interior realized for Setiakon Builders, Kuala Lumpur, Malaysia.',
    desc_zh: '為馬來西亞吉隆坡 Setiakon Builders 設計的參數化自由形體室內空間。',
    link: 'project.html?id=setiakon',
    slug: 'setiakon',
    gallery: ['assets/projects/gallery/setiakon-1.jpg','assets/projects/gallery/setiakon-2.jpg','assets/projects/gallery/setiakon-3.jpg','assets/projects/gallery/setiakon-4.jpg'],
    detail_en: ['A commissioned lobby design for construction company Setiakon Builders in Kuala Lumpur — parametric design methods generate a freeform spatial experience, carried from digital model through fabrication to the built interior.'],
    detail_zh: ['本設計案為馬來西亞吉隆坡建設公司 Setiakon Builders 之大廳委託設計—以參數設計方法生成自由形體空間，從數位模型、製造到落成，完整實現數位設計到建造的一貫流程。'],
    facts: [['2017','落成於馬來西亞吉隆坡']]
  },
  {
    title_en: 'QRcube',
    title_zh: 'QRcube 景點互動裝置',
    year: '2016',
    category: 'fab',
    image: 'assets/projects/qrcube.jpg',
    desc_en: 'Three interactive landmark installations on the YZU campus — quiet monoliths that light up as you approach.',
    desc_zh: '元智校園三處景點的互動裝置—靠近時亮起詩文與 QR 燈光的靜默量體。',
    link: 'project.html?id=qrcube',
    slug: 'qrcube',
    gallery: ['assets/projects/gallery/qrcube-1.jpg'],
    detail_en: ['QRcube comprises three interactive art installations placed at scenic spots on the YZU campus — the tree-lined boulevard, Library Building 5 and the wireless plaza. Clean and minimal, each cube stands quietly in grey and white; as someone approaches, light glows from within, revealing a QR code. Scanning it with the campus app opens poems about the site, where visitors can also photograph and share; without a phone, the poems can simply be read in the glowing light from the other side.'],
    detail_zh: ['QRcube 為放置在元智校園景點的互動裝置藝術，共三件，分別位於林蔭大道、五館圖書館及無線延續前。裝置外觀簡潔俐落，無人靠近時僅以灰與白的面貌安靜矗立；只要人一靠近，裝置便立即透出光線並顯示 QRcode—以手機 APP 掃描即可閱讀景點詩文、拍照留言上傳分享；即使沒有手機，也可從裝置另一端，觀看燈光內的詩文。'],
    facts: [['2016','元智大學校園公共藝術（林蔭大道・五館圖書館・無線延續前）']]
  },
  {
    title_en: 'Taiwan Museum Cloud — Shape of Cloud',
    title_zh: '台博雲「形。雲」',
    year: '2015',
    category: 'fab',
    image: 'assets/projects/museum-cloud.jpg',
    desc_en: 'Blow into the cloud: an interactive installation turning breath into thunder and rain, National Taiwan Museum.',
    desc_zh: '對著雲吹一口氣：把氣息化為雷雨的互動裝置，國立臺灣博物館。',
    link: 'project.html?id=museum-cloud',
    slug: 'museum-cloud',
    gallery: ['assets/projects/gallery/museum-cloud-1.jpg','assets/projects/gallery/museum-cloud-2.jpg','assets/projects/gallery/museum-cloud-3.jpg'],
    detail_en: ['Created for “Dream Museum City” at the National Taiwan Museum, the installation “Shape of Cloud” gives visual form to the auditory imagery of nature — wind, thunder and rain — through interaction.','As visitors blow into the piece, the installation gathers the formless wind and reflects it in the tangible cloud: from muffled rumbling, to lightning and thunder, to a deafening rainstorm. Formless wind as input, tangible cloud as output — like cloud computing in the digital age, data drifts into the invisible cloud, is computed, and returns in visible form.'],
    detail_zh: ['為國立臺灣博物館「夢幻博物城：一個現代性的尋夢計畫」所創作。互動裝置主題為「形。雲」—以「雲」的視覺意象，將自然界中的聽覺意象（風、雷、雨）藉由與人的互動呈現出來。','透過觀眾的吹氣，裝置集結了無形的風，反映在有形的雲：從悶雷、雷鳴電閃、到最後震耳欲聾的暴風雨。「無形風」作為輸入，「有形雲」作為輸出—猶如數位時代的雲端運算，資料傳送、儲存於無形雲端、進行運算，再由各方有形應用。'],
    facts: [['2015–16','夢幻博物城：一個現代性的尋夢計畫（國立臺灣博物館，2015.12.22–2016.09.04）']]
  },
  {
    title_en: 'HHSS — Hear your Heart, Show your Style',
    title_zh: 'HHSS 心跳互動牆（適應性皮層結構）',
    year: '2015',
    category: 'fab',
    image: 'assets/projects/hhss.jpg',
    desc_en: 'An interactive tunnel that visualizes your heartbeat through luminous smart textiles.',
    desc_zh: '以智慧發光織物把心跳視覺化的互動隧道。',
    link: 'project.html?id=hhss',
    slug: 'hhss',
    gallery: ['assets/projects/gallery/hhss-1.jpg','assets/projects/gallery/hhss-2.jpg','assets/projects/gallery/hhss-3.jpg'],
    detail_en: ['HHSS (Hear your Heart, Show your Style) is an interactive installation that visualizes physiological signals and shapes space. Entering the HHSS tunnel with music, visitors have their heartbeat sensed; luminous smart textiles by Far Eastern New Century expand and contract dynamically, like blood pulsing through vessels — as if standing inside one’s own pulse. The breathing, adaptive skin structure embodies vitality itself.'],
    detail_zh: ['HHSS（Hear your Heart, Show your Style）為一個可將生理訊號視覺化並形塑空間之互動裝置。體驗者聆聽著音樂進入 HHSS 互動隧道，裝置感測其心跳，再藉由遠東新智慧織物—發光軟性材質的動態伸縮，呈現出宛如血液進入血管的擴張與收縮，彷彿置身在自己的脈搏之中。「聆聽自己的心，展現自己的風格」，這個會呼吸的適應性皮層結構，體現出生命力。'],
    facts: [['2015','2015 高雄設計節「野設計」製造所 DesignFab Lab（高雄駁二藝術特區，至 11.22）']]
  },
  {
    title_en: 'Fuel-Cell Concept Vehicle',
    title_zh: '時尚燃料電池節能蝙蝠車',
    year: '2010',
    category: 'fab',
    image: 'assets/projects/gallery/batcar-1.jpg',
    desc_en: 'Exterior design (design director) for a fuel-cell energy-saving concept vehicle, YZU Fuel Cell Center.',
    desc_zh: '時尚燃料電池節能「蝙蝠車」外形設計（設計總監），元智燃料電池中心。',
    link: 'project.html?id=batcar',
    slug: 'batcar',
    gallery: ['assets/projects/gallery/batcar-1.jpg','assets/projects/gallery/batcar-2.jpg'],
    detail_en: ['Exterior design for a fashionable fuel-cell energy-saving concept vehicle (“Bat Car”), developed with the YZU Fuel Cell Center in 2010 — carrying digital design methods into vehicle styling as design director.'],
    detail_zh: ['2010 年與元智燃料電池中心合作之時尚燃料電池節能「蝙蝠車」外形設計，擔任設計總監—將數位設計方法帶入載具造型設計。']
  },
  {
    title_en: 'Energy House & Hsinchu Makerspace',
    title_zh: '能源屋・新竹 Makerspace 建築設計',
    year: '2015',
    category: 'fab',
    desc_en: 'Energy house design and architectural planning for a makerspace in Hsinchu (industry collaboration).',
    desc_zh: '能源屋設計與新竹 makerspace 建築設計規劃（產學合作）。',
    link: '#'
  },

  // ---------- 設計教育 / AR ----------
  {
    title_en: 'Hanzi Childhood (AR)',
    title_zh: '漢字小時候（AR 漢字教學系統）',
    year: '2018',
    category: 'edu',
    image: 'assets/projects/hanzi.jpg',
    desc_en: 'An AR app that shows Chinese characters as the pictures they once were.',
    desc_zh: '讓漢字回到「小時候」圖像模樣的 AR 學習 App。',
    award: 'ARVR 元智教育應用創作競賽 銀獎',
    award_en: 'YZU AR/VR Educational Application Competition — Silver',
    link: 'project.html?id=hanzi',
    slug: 'hanzi',
    gallery: ['assets/projects/gallery/hanzi-1.jpg','assets/projects/gallery/hanzi-2.jpg'],
    detail_en: ['Hanzi Childhood is an AR app for learning Chinese characters with mobile devices and character cards. It restores each character to its pictographic “childhood” image, capturing the picture-like beauty of hanzi — an aid for international students and schoolchildren beginning to learn Chinese.','The character forms themselves serve as the AR markers: pointing the camera at a written character instantly reveals its pictographic image, evolution and voice explanation. The system was adopted long-term in mixed-age classes at Renhe Elementary in Meishan, Chiayi, and is envisioned to grow into an everyday AR dictionary with AI-enhanced recognition.'],
    detail_zh: ['「漢字小時候」是一款結合 AR 技術學習漢字的 APP，搭配行動載具及字卡使用。系統以 AR 還原中文字「小時候」圖像的樣子，抓住漢字「象形」的特色，充分呈現漢字「如畫」的美感，作為外籍生或國小學生學習漢字的輔助教材。','此系統善用字的「形」—如畫般的中文字形本身即為 AR 偵測標記（marker），偵測後立即呈現文字的 AR 意象圖、象形演變與語音解說。系統長期導入嘉義縣梅山鄉仁和國小混齡課程；未來希望結合 AI 精進圖形辨識，延伸成為生活中的 AR 字典。'],
    facts: [['2018','與中語系、應外系跨域合作開發'],['2018','ARVR 元智大學教育應用創作競賽 銀獎'],['2018–','長期導入嘉義縣梅山鄉仁和國小混齡課程']]
  },
  {
    title_en: 'Taoyuan Pond Poetry (AR)',
    title_zh: '桃園「塘」詩（AR 詩詞教學系統）',
    year: '2018',
    category: 'edu',
    image: 'assets/projects/pond-poetry.jpg',
    desc_en: 'Experiencing pond poetry on site through AR — literature × landscape × big data.',
    desc_zh: '在埤塘現場以 AR 體驗詩詞意境—文學 × 地景 × 大數據。',
    link: 'project.html?id=pond-poetry',
    slug: 'pond-poetry',
    gallery: ['assets/projects/gallery/pond-poetry-1.jpg','assets/projects/gallery/pond-poetry-2.jpg','assets/projects/gallery/pond-poetry-3.jpg'],
    detail_en: ['Co-developed by Prof. Chor-Kheng Lim (Art & Design) and Prof. Huang Zhi-Ming (Chinese Linguistics) — design and literature in cross-disciplinary collaboration. Using big data and AR, the system builds a field-experience teaching tool that combines pond landscape culture with classical poetry, letting students experience poetic imagery in AR-augmented real space.','Based on Prof. Huang’s research on Taiwan pond poetry, the CKfablab team classified the poems by imagery, mapped each pond’s geographic location, and generated word-cloud analyses of the scenes and objects each imagery type evokes — making literature learning livelier and more deeply felt.'],
    detail_zh: ['由藝術與設計系林楚卿教授及中語系黃智明助理教授共同開發—設計與文學的跨域合作。藉由大數據及 AR 技術，開發場域體驗的文學教學工具，結合地景文化與詩詞的互動教學媒材，讓學生實地以 AR 實虛共構的空間體驗詩詞意境，深入領悟詩人所表達的意象。','基於黃教授對台灣埤塘詩詞的研究與整理，CKfablab 設計團隊將所有詩詞進行意象分類、找出對應埤塘的地理位置，並以大數據產生詞雲分析，細分不同意象類型中詩詞常用的景象與物件。'],
    facts: [['2018','與中語系跨域合作開發'],['2018','ARVR 元智大學教育應用創作競賽 佳作']]
  },
  {
    title_en: 'NEXT — Chinese Culture E-Learning (AR)',
    title_zh: 'NEXT 中華文化e點通（AR 操作教學系統）',
    year: '2019',
    category: 'edu',
    image: 'assets/projects/next.jpg',
    desc_en: 'AR step-by-step guidance on physical teaching aids — like having a master by your side.',
    desc_zh: '在實體教具上做 AR 步驟引導—如同師父在身邊的模擬教學。',
    link: 'project.html?id=next',
    slug: 'next',
    gallery: ['assets/projects/gallery/next-1.jpg','assets/projects/gallery/next-2.jpg'],
    detail_en: ['NEXT pairs AR with physical teaching aids carrying special markers. The system detects the current step of the physical model in real time and guides the learner to the “next” operation with animation and voice explanation — every step guided in the moment, like a master teaching by your side. The NEXT series later evolved into the MOE Teaching Practice Research project on tangible electronics learning.'],
    detail_zh: ['此教學系統運用 AR 技術，搭配具有特殊標記（marker）的實體教具／模型：AR 即時偵測實體模型目前的操作步驟狀態，並以動畫與語音解說提供「下一步」的操作引導，讓每一步驟都能被及時引導，如同有專家或傳統師父在身邊的模擬教學。NEXT 系列後續延伸為教育部教學實踐研究計畫之實體運算電子電路學習系統。'],
    facts: [['2019','ARVR 元智大學教育應用創作競賽 特優（NEXT 系列連續四屆特優）']]
  },
  {
    title_en: 'Maker Car',
    title_zh: '創客快閃車 Maker Car',
    year: '2018',
    category: 'edu',
    image: 'assets/projects/maker-car.jpg',
    desc_en: 'A mobile mini maker-base: a transforming tricycle that carries 3D printers and laser cutters to communities.',
    desc_zh: '行動創客迷你基地：載著 3D 印表機與雷切機進社區的變形三輪車。',
    link: 'project.html?id=maker-car',
    slug: 'maker-car',
    gallery: ['assets/projects/gallery/maker-car-1.jpg','assets/projects/gallery/maker-car-2.jpg','assets/projects/gallery/maker-car-3.jpg'],
    detail_en: ['Maker Car is a mobile mini maker-base — a tricycle that carries a 3D printer and laser cutter out to run workshops. The vehicle itself embodies the digital-maker spirit: an electric tricycle transformed through digital design and fabrication, with every component 3D-printed, laser-cut or CNC-machined, then precisely assembled. Its panels unfold like a transformer to display works.','With the idea of “a maker base that comes to you”, Maker Car extends the fixed makerspace into communities — pop-up activities include laser-cut custom objects and 3D-printed mini planters, letting residents experience digital fabrication first-hand.'],
    detail_zh: ['「行動創客快閃車」是一個行動創客迷你基地，車子載著 3D 印表機及雷射切割機外出辦工作坊。車子本身展現數位自造（digital maker）的創意精神：以數位設計與製造方式將一台電動三輪車改造成創客車，所有設計元件皆以 3D 列印、雷射切割、CNC 製作，再精準組裝，完全客製化設計；車身面板如變形金剛般可自由展開擺放作品。','以「創客基地到你家」的想法，延伸定點式創客空間的使用功能，提供民眾了解及體驗數位製造的機會—快閃活動包含雷射切割客製化物件與 3D 列印小花盆等，尤其能進入社區讓居民共同參與。'],
    facts: [['2018','2018 創客嘉年華會（Maker Faire）展出']]
  },
  {
    title_en: 'YZU 30th Anniversary Gift',
    title_zh: '元智 30 週年紀念品',
    year: '2019',
    category: 'edu',
    image: 'assets/projects/yzu30.jpg',
    desc_en: 'Designed and fabricated entirely at the YZU Maker Base — point, line and plane in cold light.',
    desc_zh: '從設計到製造全程於元智創客基地完成—點、線、面與冷光。',
    link: 'project.html?id=yzu30',
    slug: 'yzu30',
    gallery: ['assets/projects/gallery/yzu30-1.jpg','assets/projects/gallery/yzu30-2.jpg'],
    detail_en: ['CKfablab designed this commemorative gift for YZU’s 30th anniversary under the principle of “design it ourselves, make it ourselves” — one month from design to small-batch production, entirely within the YZU Maker Base.','Form: a composition of point, line and plane — transparent folded planes form a stable structure; electroluminescent wire folds out Y, Z and U from three directions; three nodes lock every element precisely. Fabrication: SLA 3D-printed nodes, laser-cut acrylic planes, tubes and packaging, CNC-milled pine base. Function: it doubles as a phone stand — the cold-light wire glows when a phone is placed.'],
    detail_zh: ['此作品為 CKfablab 團隊為元智 30 週年所設計的紀念品。堅守「自己設計、自己製造」的理念，為期一個月，從設計到小量製造皆在元智創客基地完成。','【造型】由點、線、面組合而成：透明折面形成穩定結構；冷光線從三個不同面向折出 Y、Z、U；由三個節點將各元件精準固定。【數位製造】從紀念品到包裝紙盒，所有元件皆由創客基地生產：光固化 3D 列印固定節點、雷射切割壓克力折面／線管／包裝盒、CNC 切削松木底座。【功能】可作為手機架，手機置放時冷光線會發亮。'],
    facts: [['2019','元智大學 30 週年校慶紀念品']]
  },

  // ---------- 建築與展覽（AleppoZONE 時期－2010）----------
  {
    title_en: 'Calligraphic House',
    title_zh: '水墨狂草・狂草住屋',
    year: '2007–08',
    category: 'arch',
    image: 'assets/projects/calligraphic-house.jpg',
    desc_en: 'Calligraphy-inspired freeform house for the Aodi NEXT GENE international architecture project; published in New Trends of Architecture in Europe and Asia-Pacific (design director).',
    desc_zh: '澳底大地建築國際計畫之狂草建築設計（設計總監），收錄於《New Trends of Architecture in Europe and Asia-Pacific》。',
    link: '#'
  },
  {
    title_en: 'Venice Architecture Biennale — H2O Life: Flexible Tube',
    title_zh: '威尼斯建築雙年展 H2O Life: Flexible Tube',
    year: '2008',
    category: 'arch',
    desc_en: 'Exhibiting designer, the 11th International Architecture Exhibition, La Biennale di Venezia.',
    desc_zh: '第 11 屆威尼斯建築雙年展參展設計師。',
    link: '#'
  },
  {
    title_en: 'AleppoZONE',
    title_zh: 'AleppoZONE',
    year: '2003–08',
    category: 'arch',
    image: 'assets/projects/aleppozone.jpg',
    desc_en: 'Large-scale digital architecture as core designer then project leader — Qingdao University Town, Dalian Electronics HQ and more.',
    desc_zh: '學生時期以核心設計師至 Project Leader 身分參與的數位建築設計案。',
    link: 'project.html?id=aleppozone',
    slug: 'aleppozone',
    gallery: ['assets/projects/gallery/aleppozone-1.jpg','assets/projects/gallery/aleppozone-2.jpg','assets/projects/gallery/aleppozone-3.jpg','assets/projects/gallery/aleppozone-4.jpg'],
    detail_en: ['During graduate school at NCTU, CK served in the AleppoZONE digital architecture team — from core designer (2003–05) to project leader (2006–08) — delivering large-scale digital architecture and exhibition projects across Taiwan, China, Italy and Japan.','Key works include the Qingdao University Town Center, Qingdao Administrative Center, the Dalian Electronics headquarters with its freeform lobby, the calligraphy-inspired spaces of Dan-Shui Yesterday for painter Chen Hui-Kun’s centennial, and exhibition design for the Gaudí 3G exhibition and the Museum of Tomorrow at TFAM.'],
    detail_zh: ['研究所時期，CK 於 AleppoZONE 數位建築團隊歷任核心設計師（2003–05）至 Project Leader（2006–08），完成橫跨台灣、中國、義大利與日本的大型數位建築與展覽設計案。','代表作包括青島大學城中心、青島行政中心、大連電子公司辦公總部（自由形體大廳）、為畫家陳慧坤百歲展設計的「昨日淡水」繪畫空間，以及高第 3G 時空展、北美館明日建築展等展場設計。'],
    facts: [['2008','第 11 屆威尼斯建築雙年展 H2O Life: Flexible Tube 參展設計師'],['2008','歐亞建築新潮流 2008–2009 巡迴展（東京，策展人 Peter Cook、伊東豊雄）'],['2007','明日建築展 展場設計總監（臺北市立美術館）'],['2006','高第 3G 時空展 展場設計總監（國父紀念館）・昨日淡水（國立台灣美術館）']]
  },
  {
    title_en: 'Exhibition Design Series',
    title_zh: '展場設計系列',
    year: '2002–07',
    category: 'arch',
    image: 'assets/projects/exhibition-design.jpg',
    desc_en: 'Exhibition design director for the Gaudí 3G exhibition (2006), Museum of Tomorrow architecture exhibition at TFAM (2007), Florence architecture exhibitions and the Shenzhen Biennale.',
    desc_zh: '展場設計總監作品：高第建築藝術展（2006）、北美館明日建築展（2007）、佛羅倫斯建築影像展、深圳城市與建築雙年展等。',
    link: '#'
  }
];
